//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Tests.Interfaces.indexationged {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IndexationGEDSoap", Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class IndexationGED : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IndexationListeDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IntegrationListeDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IndexationGED() {
            this.Url = global::Tests.Interfaces.Properties.Settings.Default.Tests_Interfaces_indexationged_IndexationGED;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IndexationListeDocumentCompletedEventHandler IndexationListeDocumentCompleted;
        
        /// <remarks/>
        public event IntegrationListeDocumentCompletedEventHandler IntegrationListeDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx/IndexationListe" +
            "Document", RequestNamespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx", ResponseNamespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListeIndexationDocumentResponse IndexationListeDocument(string context, IndexationDocument[] listeIndexDoc, string entite) {
            object[] results = this.Invoke("IndexationListeDocument", new object[] {
                        context,
                        listeIndexDoc,
                        entite});
            return ((ListeIndexationDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IndexationListeDocumentAsync(string context, IndexationDocument[] listeIndexDoc, string entite) {
            this.IndexationListeDocumentAsync(context, listeIndexDoc, entite, null);
        }
        
        /// <remarks/>
        public void IndexationListeDocumentAsync(string context, IndexationDocument[] listeIndexDoc, string entite, object userState) {
            if ((this.IndexationListeDocumentOperationCompleted == null)) {
                this.IndexationListeDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndexationListeDocumentOperationCompleted);
            }
            this.InvokeAsync("IndexationListeDocument", new object[] {
                        context,
                        listeIndexDoc,
                        entite}, this.IndexationListeDocumentOperationCompleted, userState);
        }
        
        private void OnIndexationListeDocumentOperationCompleted(object arg) {
            if ((this.IndexationListeDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IndexationListeDocumentCompleted(this, new IndexationListeDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx/IntegrationList" +
            "eDocument", RequestNamespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx", ResponseNamespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListeIntegrationDocumentResponse IntegrationListeDocument(IntegrationDocument[] listeIntegDoc, string entite) {
            object[] results = this.Invoke("IntegrationListeDocument", new object[] {
                        listeIntegDoc,
                        entite});
            return ((ListeIntegrationDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IntegrationListeDocumentAsync(IntegrationDocument[] listeIntegDoc, string entite) {
            this.IntegrationListeDocumentAsync(listeIntegDoc, entite, null);
        }
        
        /// <remarks/>
        public void IntegrationListeDocumentAsync(IntegrationDocument[] listeIntegDoc, string entite, object userState) {
            if ((this.IntegrationListeDocumentOperationCompleted == null)) {
                this.IntegrationListeDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIntegrationListeDocumentOperationCompleted);
            }
            this.InvokeAsync("IntegrationListeDocument", new object[] {
                        listeIntegDoc,
                        entite}, this.IntegrationListeDocumentOperationCompleted, userState);
        }
        
        private void OnIntegrationListeDocumentOperationCompleted(object arg) {
            if ((this.IntegrationListeDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IntegrationListeDocumentCompleted(this, new IntegrationListeDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class IndexationDocument {
        
        private int iD_DocumentNortiaField;
        
        private string iD_DocumentSalesForceField;
        
        private string typeDocumentField;
        
        private int iD_PliNortiaField;
        
        private string typeActeField;
        
        private string typeObjetAvenantField;
        
        private string iD_PliSalesForceField;
        
        private bool visibleNOLField;
        
        /// <remarks/>
        public int ID_DocumentNortia {
            get {
                return this.iD_DocumentNortiaField;
            }
            set {
                this.iD_DocumentNortiaField = value;
            }
        }
        
        /// <remarks/>
        public string ID_DocumentSalesForce {
            get {
                return this.iD_DocumentSalesForceField;
            }
            set {
                this.iD_DocumentSalesForceField = value;
            }
        }
        
        /// <remarks/>
        public string TypeDocument {
            get {
                return this.typeDocumentField;
            }
            set {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        public int ID_PliNortia {
            get {
                return this.iD_PliNortiaField;
            }
            set {
                this.iD_PliNortiaField = value;
            }
        }
        
        /// <remarks/>
        public string TypeActe {
            get {
                return this.typeActeField;
            }
            set {
                this.typeActeField = value;
            }
        }
        
        /// <remarks/>
        public string TypeObjetAvenant {
            get {
                return this.typeObjetAvenantField;
            }
            set {
                this.typeObjetAvenantField = value;
            }
        }
        
        /// <remarks/>
        public string ID_PliSalesForce {
            get {
                return this.iD_PliSalesForceField;
            }
            set {
                this.iD_PliSalesForceField = value;
            }
        }
        
        /// <remarks/>
        public bool VisibleNOL {
            get {
                return this.visibleNOLField;
            }
            set {
                this.visibleNOLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class IntegrationDocumentResponse {
        
        private int indexField;
        
        private int iD_PliNortiaField;
        
        private int iD_DocumentNortiaField;
        
        private int nbPageField;
        
        private int codeRetourField;
        
        private string messageField;
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public int ID_PliNortia {
            get {
                return this.iD_PliNortiaField;
            }
            set {
                this.iD_PliNortiaField = value;
            }
        }
        
        /// <remarks/>
        public int ID_DocumentNortia {
            get {
                return this.iD_DocumentNortiaField;
            }
            set {
                this.iD_DocumentNortiaField = value;
            }
        }
        
        /// <remarks/>
        public int NbPage {
            get {
                return this.nbPageField;
            }
            set {
                this.nbPageField = value;
            }
        }
        
        /// <remarks/>
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class ListeIntegrationDocumentResponse {
        
        private int codeRetourField;
        
        private string messageField;
        
        private string entiteField;
        
        private IntegrationDocumentResponse[] documentResponseField;
        
        /// <remarks/>
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string entite {
            get {
                return this.entiteField;
            }
            set {
                this.entiteField = value;
            }
        }
        
        /// <remarks/>
        public IntegrationDocumentResponse[] documentResponse {
            get {
                return this.documentResponseField;
            }
            set {
                this.documentResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class IntegrationDocument {
        
        private int indexField;
        
        private string iD_ActeSalesforceField;
        
        private string nomDocumentField;
        
        private string extensionDocumentField;
        
        private string typeActeField;
        
        private string typeDocumentField;
        
        private bool visibleNOLField;
        
        private byte[] dataDocumentField;
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string ID_ActeSalesforce {
            get {
                return this.iD_ActeSalesforceField;
            }
            set {
                this.iD_ActeSalesforceField = value;
            }
        }
        
        /// <remarks/>
        public string NomDocument {
            get {
                return this.nomDocumentField;
            }
            set {
                this.nomDocumentField = value;
            }
        }
        
        /// <remarks/>
        public string ExtensionDocument {
            get {
                return this.extensionDocumentField;
            }
            set {
                this.extensionDocumentField = value;
            }
        }
        
        /// <remarks/>
        public string TypeActe {
            get {
                return this.typeActeField;
            }
            set {
                this.typeActeField = value;
            }
        }
        
        /// <remarks/>
        public string TypeDocument {
            get {
                return this.typeDocumentField;
            }
            set {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        public bool VisibleNOL {
            get {
                return this.visibleNOLField;
            }
            set {
                this.visibleNOLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DataDocument {
            get {
                return this.dataDocumentField;
            }
            set {
                this.dataDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class IndexationDocumentResponse {
        
        private int iD_DocumentNortiaField;
        
        private string iD_DocumentSalesForceField;
        
        private int codeRetourField;
        
        private string messageField;
        
        /// <remarks/>
        public int ID_DocumentNortia {
            get {
                return this.iD_DocumentNortiaField;
            }
            set {
                this.iD_DocumentNortiaField = value;
            }
        }
        
        /// <remarks/>
        public string ID_DocumentSalesForce {
            get {
                return this.iD_DocumentSalesForceField;
            }
            set {
                this.iD_DocumentSalesForceField = value;
            }
        }
        
        /// <remarks/>
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/IndexationGED/IndexationGED.asmx")]
    public partial class ListeIndexationDocumentResponse {
        
        private int codeRetourField;
        
        private string messageField;
        
        private string contextField;
        
        private string entiteField;
        
        private IndexationDocumentResponse[] documentResponseField;
        
        /// <remarks/>
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
            }
        }
        
        /// <remarks/>
        public string entite {
            get {
                return this.entiteField;
            }
            set {
                this.entiteField = value;
            }
        }
        
        /// <remarks/>
        public IndexationDocumentResponse[] documentResponse {
            get {
                return this.documentResponseField;
            }
            set {
                this.documentResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IndexationListeDocumentCompletedEventHandler(object sender, IndexationListeDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IndexationListeDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IndexationListeDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListeIndexationDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListeIndexationDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IntegrationListeDocumentCompletedEventHandler(object sender, IntegrationListeDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IntegrationListeDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IntegrationListeDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListeIntegrationDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListeIntegrationDocumentResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591