//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Tests.Interfaces.genererProdLocal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GenerationProdSoap", Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class GenerationProd : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenererProdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GenerationProd() {
            this.Url = global::Tests.Interfaces.Properties.Settings.Default.Tests_Interfaces_genererProdLocal_GenerationProd;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenererProdCompletedEventHandler GenererProdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx/GenererProd", RequestNamespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx", ResponseNamespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GenererProdResponse GenererProd(string IDProd, string codeCompagnie, Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification) {
            object[] results = this.Invoke("GenererProd", new object[] {
                        IDProd,
                        codeCompagnie,
                        listeActe,
                        typeEnvoi,
                        genererProdActe,
                        classification});
            return ((GenererProdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GenererProdAsync(string IDProd, string codeCompagnie, Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification) {
            this.GenererProdAsync(IDProd, codeCompagnie, listeActe, typeEnvoi, genererProdActe, classification, null);
        }
        
        /// <remarks/>
        public void GenererProdAsync(string IDProd, string codeCompagnie, Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification, object userState) {
            if ((this.GenererProdOperationCompleted == null)) {
                this.GenererProdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenererProdOperationCompleted);
            }
            this.InvokeAsync("GenererProd", new object[] {
                        IDProd,
                        codeCompagnie,
                        listeActe,
                        typeEnvoi,
                        genererProdActe,
                        classification}, this.GenererProdOperationCompleted, userState);
        }
        
        private void OnGenererProdOperationCompleted(object arg) {
            if ((this.GenererProdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenererProdCompleted(this, new GenererProdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class Acte {
        
        private bool isSignedField;
        
        private string prodActeIDField;
        
        private string nomTypeField;
        
        private string nomActeAdministratifField;
        
        private string referenceInterneField;
        
        private string nomCompletSouscripteursField;
        
        private string numContratField;
        
        private string codeApporteurField;
        
        private string nomApporteurField;
        
        private float montantBrutField;
        
        private string typeFraisField;
        
        private float fraisField;
        
        private string iD_ProfilCompagnieField;
        
        private string nomEnveloppeField;
        
        private Repartition[] listeSupportDesinvestirField;
        
        private Repartition[] listeSupportInvestirField;
        
        private DocumentProduction[] listeDocumentField;
        
        private bool isTraitementEdiField;
        
        private System.DateTime dateCreationField;
        
        private System.DateTime dateAcquisitionField;
        
        private System.DateTime dateEnvoiProductionField;
        
        private string commentaireField;
        
        private bool investissementImmediatField;
        
        private bool regulField;
        
        /// <remarks/>
        public bool isSigned {
            get {
                return this.isSignedField;
            }
            set {
                this.isSignedField = value;
            }
        }
        
        /// <remarks/>
        public string prodActeID {
            get {
                return this.prodActeIDField;
            }
            set {
                this.prodActeIDField = value;
            }
        }
        
        /// <remarks/>
        public string NomType {
            get {
                return this.nomTypeField;
            }
            set {
                this.nomTypeField = value;
            }
        }
        
        /// <remarks/>
        public string NomActeAdministratif {
            get {
                return this.nomActeAdministratifField;
            }
            set {
                this.nomActeAdministratifField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceInterne {
            get {
                return this.referenceInterneField;
            }
            set {
                this.referenceInterneField = value;
            }
        }
        
        /// <remarks/>
        public string NomCompletSouscripteurs {
            get {
                return this.nomCompletSouscripteursField;
            }
            set {
                this.nomCompletSouscripteursField = value;
            }
        }
        
        /// <remarks/>
        public string NumContrat {
            get {
                return this.numContratField;
            }
            set {
                this.numContratField = value;
            }
        }
        
        /// <remarks/>
        public string CodeApporteur {
            get {
                return this.codeApporteurField;
            }
            set {
                this.codeApporteurField = value;
            }
        }
        
        /// <remarks/>
        public string NomApporteur {
            get {
                return this.nomApporteurField;
            }
            set {
                this.nomApporteurField = value;
            }
        }
        
        /// <remarks/>
        public float MontantBrut {
            get {
                return this.montantBrutField;
            }
            set {
                this.montantBrutField = value;
            }
        }
        
        /// <remarks/>
        public string TypeFrais {
            get {
                return this.typeFraisField;
            }
            set {
                this.typeFraisField = value;
            }
        }
        
        /// <remarks/>
        public float Frais {
            get {
                return this.fraisField;
            }
            set {
                this.fraisField = value;
            }
        }
        
        /// <remarks/>
        public string ID_ProfilCompagnie {
            get {
                return this.iD_ProfilCompagnieField;
            }
            set {
                this.iD_ProfilCompagnieField = value;
            }
        }
        
        /// <remarks/>
        public string NomEnveloppe {
            get {
                return this.nomEnveloppeField;
            }
            set {
                this.nomEnveloppeField = value;
            }
        }
        
        /// <remarks/>
        public Repartition[] ListeSupportDesinvestir {
            get {
                return this.listeSupportDesinvestirField;
            }
            set {
                this.listeSupportDesinvestirField = value;
            }
        }
        
        /// <remarks/>
        public Repartition[] ListeSupportInvestir {
            get {
                return this.listeSupportInvestirField;
            }
            set {
                this.listeSupportInvestirField = value;
            }
        }
        
        /// <remarks/>
        public DocumentProduction[] ListeDocument {
            get {
                return this.listeDocumentField;
            }
            set {
                this.listeDocumentField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTraitementEdi {
            get {
                return this.isTraitementEdiField;
            }
            set {
                this.isTraitementEdiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateAcquisition {
            get {
                return this.dateAcquisitionField;
            }
            set {
                this.dateAcquisitionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnvoiProduction {
            get {
                return this.dateEnvoiProductionField;
            }
            set {
                this.dateEnvoiProductionField = value;
            }
        }
        
        /// <remarks/>
        public string Commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
            }
        }
        
        /// <remarks/>
        public bool InvestissementImmediat {
            get {
                return this.investissementImmediatField;
            }
            set {
                this.investissementImmediatField = value;
            }
        }
        
        /// <remarks/>
        public bool Regul {
            get {
                return this.regulField;
            }
            set {
                this.regulField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class Repartition {
        
        private string code_support_extField;
        
        private string codeISINField;
        
        private string typeRepartitionField;
        
        private float valeurRepartitionField;
        
        /// <remarks/>
        public string code_support_ext {
            get {
                return this.code_support_extField;
            }
            set {
                this.code_support_extField = value;
            }
        }
        
        /// <remarks/>
        public string CodeISIN {
            get {
                return this.codeISINField;
            }
            set {
                this.codeISINField = value;
            }
        }
        
        /// <remarks/>
        public string TypeRepartition {
            get {
                return this.typeRepartitionField;
            }
            set {
                this.typeRepartitionField = value;
            }
        }
        
        /// <remarks/>
        public float ValeurRepartition {
            get {
                return this.valeurRepartitionField;
            }
            set {
                this.valeurRepartitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class GenererProdResponse {
        
        private string iDProdField;
        
        private int codeRetourField;
        
        private string messageField;
        
        /// <remarks/>
        public string IDProd {
            get {
                return this.iDProdField;
            }
            set {
                this.iDProdField = value;
            }
        }
        
        /// <remarks/>
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class DocumentProduction {
        
        private int iD_DocumentNortiaField;
        
        private string iD_DocumentSalesForceField;
        
        private int nbPageField;
        
        /// <remarks/>
        public int ID_DocumentNortia {
            get {
                return this.iD_DocumentNortiaField;
            }
            set {
                this.iD_DocumentNortiaField = value;
            }
        }
        
        /// <remarks/>
        public string ID_DocumentSalesForce {
            get {
                return this.iD_DocumentSalesForceField;
            }
            set {
                this.iD_DocumentSalesForceField = value;
            }
        }
        
        /// <remarks/>
        public int NbPage {
            get {
                return this.nbPageField;
            }
            set {
                this.nbPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GenererProdCompletedEventHandler(object sender, GenererProdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenererProdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenererProdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GenererProdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenererProdResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591