//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Interfaces.GenererProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx", ConfigurationName="GenererProd.GenerationProdSoap")]
    public interface GenerationProdSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx/GenererProd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Tests.Interfaces.GenererProd.GenererProdResponse GenererProd(string IDProd, string codeCompagnie, Tests.Interfaces.GenererProd.Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx/GenererProd", ReplyAction="*")]
        System.Threading.Tasks.Task<Tests.Interfaces.GenererProd.GenererProdResponse> GenererProdAsync(string IDProd, string codeCompagnie, Tests.Interfaces.GenererProd.Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class Acte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomTypeField;
        
        private string nomActeAdministratifField;
        
        private string referenceInterneField;
        
        private string nomCompletSouscripteursField;
        
        private string numContratField;
        
        private string codeApporteurField;
        
        private string nomApporteurField;
        
        private float montantBrutField;
        
        private string typeFraisField;
        
        private float fraisField;
        
        private string iD_ProfilCompagnieField;
        
        private string nomEnveloppeField;
        
        private Repartition[] listeSupportDesinvestirField;
        
        private Repartition[] listeSupportInvestirField;
        
        private DocumentProduction[] listeDocumentField;
        
        private bool isTraitementEdiField;
        
        private System.DateTime dateCreationField;
        
        private System.DateTime dateAcquisitionField;
        
        private System.DateTime dateEnvoiProductionField;
        
        private string commentaireField;
        
        private bool investissementImmediatField;
        
        private bool regulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NomType {
            get {
                return this.nomTypeField;
            }
            set {
                this.nomTypeField = value;
                this.RaisePropertyChanged("NomType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NomActeAdministratif {
            get {
                return this.nomActeAdministratifField;
            }
            set {
                this.nomActeAdministratifField = value;
                this.RaisePropertyChanged("NomActeAdministratif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceInterne {
            get {
                return this.referenceInterneField;
            }
            set {
                this.referenceInterneField = value;
                this.RaisePropertyChanged("ReferenceInterne");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NomCompletSouscripteurs {
            get {
                return this.nomCompletSouscripteursField;
            }
            set {
                this.nomCompletSouscripteursField = value;
                this.RaisePropertyChanged("NomCompletSouscripteurs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumContrat {
            get {
                return this.numContratField;
            }
            set {
                this.numContratField = value;
                this.RaisePropertyChanged("NumContrat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodeApporteur {
            get {
                return this.codeApporteurField;
            }
            set {
                this.codeApporteurField = value;
                this.RaisePropertyChanged("CodeApporteur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NomApporteur {
            get {
                return this.nomApporteurField;
            }
            set {
                this.nomApporteurField = value;
                this.RaisePropertyChanged("NomApporteur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float MontantBrut {
            get {
                return this.montantBrutField;
            }
            set {
                this.montantBrutField = value;
                this.RaisePropertyChanged("MontantBrut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TypeFrais {
            get {
                return this.typeFraisField;
            }
            set {
                this.typeFraisField = value;
                this.RaisePropertyChanged("TypeFrais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public float Frais {
            get {
                return this.fraisField;
            }
            set {
                this.fraisField = value;
                this.RaisePropertyChanged("Frais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ID_ProfilCompagnie {
            get {
                return this.iD_ProfilCompagnieField;
            }
            set {
                this.iD_ProfilCompagnieField = value;
                this.RaisePropertyChanged("ID_ProfilCompagnie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NomEnveloppe {
            get {
                return this.nomEnveloppeField;
            }
            set {
                this.nomEnveloppeField = value;
                this.RaisePropertyChanged("NomEnveloppe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public Repartition[] ListeSupportDesinvestir {
            get {
                return this.listeSupportDesinvestirField;
            }
            set {
                this.listeSupportDesinvestirField = value;
                this.RaisePropertyChanged("ListeSupportDesinvestir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public Repartition[] ListeSupportInvestir {
            get {
                return this.listeSupportInvestirField;
            }
            set {
                this.listeSupportInvestirField = value;
                this.RaisePropertyChanged("ListeSupportInvestir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public DocumentProduction[] ListeDocument {
            get {
                return this.listeDocumentField;
            }
            set {
                this.listeDocumentField = value;
                this.RaisePropertyChanged("ListeDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsTraitementEdi {
            get {
                return this.isTraitementEdiField;
            }
            set {
                this.isTraitementEdiField = value;
                this.RaisePropertyChanged("IsTraitementEdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime DateCreation {
            get {
                return this.dateCreationField;
            }
            set {
                this.dateCreationField = value;
                this.RaisePropertyChanged("DateCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime DateAcquisition {
            get {
                return this.dateAcquisitionField;
            }
            set {
                this.dateAcquisitionField = value;
                this.RaisePropertyChanged("DateAcquisition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime DateEnvoiProduction {
            get {
                return this.dateEnvoiProductionField;
            }
            set {
                this.dateEnvoiProductionField = value;
                this.RaisePropertyChanged("DateEnvoiProduction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Commentaire {
            get {
                return this.commentaireField;
            }
            set {
                this.commentaireField = value;
                this.RaisePropertyChanged("Commentaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool InvestissementImmediat {
            get {
                return this.investissementImmediatField;
            }
            set {
                this.investissementImmediatField = value;
                this.RaisePropertyChanged("InvestissementImmediat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Regul {
            get {
                return this.regulField;
            }
            set {
                this.regulField = value;
                this.RaisePropertyChanged("Regul");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class Repartition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string code_support_extField;
        
        private string codeISINField;
        
        private string typeRepartitionField;
        
        private float valeurRepartitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code_support_ext {
            get {
                return this.code_support_extField;
            }
            set {
                this.code_support_extField = value;
                this.RaisePropertyChanged("code_support_ext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodeISIN {
            get {
                return this.codeISINField;
            }
            set {
                this.codeISINField = value;
                this.RaisePropertyChanged("CodeISIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TypeRepartition {
            get {
                return this.typeRepartitionField;
            }
            set {
                this.typeRepartitionField = value;
                this.RaisePropertyChanged("TypeRepartition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float ValeurRepartition {
            get {
                return this.valeurRepartitionField;
            }
            set {
                this.valeurRepartitionField = value;
                this.RaisePropertyChanged("ValeurRepartition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class GenererProdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDProdField;
        
        private int codeRetourField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IDProd {
            get {
                return this.iDProdField;
            }
            set {
                this.iDProdField = value;
                this.RaisePropertyChanged("IDProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int codeRetour {
            get {
                return this.codeRetourField;
            }
            set {
                this.codeRetourField = value;
                this.RaisePropertyChanged("codeRetour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qualif-extranet.nortia.fr/GenerationProd/GenerationProd.asmx")]
    public partial class DocumentProduction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int iD_DocumentNortiaField;
        
        private string iD_DocumentSalesForceField;
        
        private int nbPageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID_DocumentNortia {
            get {
                return this.iD_DocumentNortiaField;
            }
            set {
                this.iD_DocumentNortiaField = value;
                this.RaisePropertyChanged("ID_DocumentNortia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID_DocumentSalesForce {
            get {
                return this.iD_DocumentSalesForceField;
            }
            set {
                this.iD_DocumentSalesForceField = value;
                this.RaisePropertyChanged("ID_DocumentSalesForce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NbPage {
            get {
                return this.nbPageField;
            }
            set {
                this.nbPageField = value;
                this.RaisePropertyChanged("NbPage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenerationProdSoapChannel : Tests.Interfaces.GenererProd.GenerationProdSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerationProdSoapClient : System.ServiceModel.ClientBase<Tests.Interfaces.GenererProd.GenerationProdSoap>, Tests.Interfaces.GenererProd.GenerationProdSoap {
        
        public GenerationProdSoapClient() {
        }
        
        public GenerationProdSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerationProdSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerationProdSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerationProdSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tests.Interfaces.GenererProd.GenererProdResponse GenererProd(string IDProd, string codeCompagnie, Tests.Interfaces.GenererProd.Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification) {
            return base.Channel.GenererProd(IDProd, codeCompagnie, listeActe, typeEnvoi, genererProdActe, classification);
        }
        
        public System.Threading.Tasks.Task<Tests.Interfaces.GenererProd.GenererProdResponse> GenererProdAsync(string IDProd, string codeCompagnie, Tests.Interfaces.GenererProd.Acte[] listeActe, string typeEnvoi, bool genererProdActe, string classification) {
            return base.Channel.GenererProdAsync(IDProd, codeCompagnie, listeActe, typeEnvoi, genererProdActe, classification);
        }
    }
}
